// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.24.1
// source: proto/test.proto

package errortest

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	ErrorTest_ErrorTest_FullMethodName = "/errortest.ErrorTest/ErrorTest"
)

// ErrorTestClient is the client API for ErrorTest service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ErrorTestClient interface {
	ErrorTest(ctx context.Context, in *EmptyMsg, opts ...grpc.CallOption) (*StatusMsg, error)
}

type errorTestClient struct {
	cc grpc.ClientConnInterface
}

func NewErrorTestClient(cc grpc.ClientConnInterface) ErrorTestClient {
	return &errorTestClient{cc}
}

func (c *errorTestClient) ErrorTest(ctx context.Context, in *EmptyMsg, opts ...grpc.CallOption) (*StatusMsg, error) {
	out := new(StatusMsg)
	err := c.cc.Invoke(ctx, ErrorTest_ErrorTest_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ErrorTestServer is the server API for ErrorTest service.
// All implementations must embed UnimplementedErrorTestServer
// for forward compatibility
type ErrorTestServer interface {
	ErrorTest(context.Context, *EmptyMsg) (*StatusMsg, error)
	mustEmbedUnimplementedErrorTestServer()
}

// UnimplementedErrorTestServer must be embedded to have forward compatible implementations.
type UnimplementedErrorTestServer struct {
}

func (UnimplementedErrorTestServer) ErrorTest(context.Context, *EmptyMsg) (*StatusMsg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ErrorTest not implemented")
}
func (UnimplementedErrorTestServer) mustEmbedUnimplementedErrorTestServer() {}

// UnsafeErrorTestServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ErrorTestServer will
// result in compilation errors.
type UnsafeErrorTestServer interface {
	mustEmbedUnimplementedErrorTestServer()
}

func RegisterErrorTestServer(s grpc.ServiceRegistrar, srv ErrorTestServer) {
	s.RegisterService(&ErrorTest_ServiceDesc, srv)
}

func _ErrorTest_ErrorTest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ErrorTestServer).ErrorTest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ErrorTest_ErrorTest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ErrorTestServer).ErrorTest(ctx, req.(*EmptyMsg))
	}
	return interceptor(ctx, in, info, handler)
}

// ErrorTest_ServiceDesc is the grpc.ServiceDesc for ErrorTest service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ErrorTest_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "errortest.ErrorTest",
	HandlerType: (*ErrorTestServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ErrorTest",
			Handler:    _ErrorTest_ErrorTest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/test.proto",
}
